# Generated by Django 6.1.1 on 2026-09-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price_ore', models.PositiveIntegerField()),
                ('products', models.JSONField(default=list)),
            ],
        ),
    ]
